"""
SQLAlchemy ORM model for the `recommendations` table.

Recommendations are actionable, evidence-backed suggestions generated by the
intelligence engine to mitigate identified knowledge risks.
"""
from __future__ import annotations

import uuid

from sqlalchemy import ARRAY, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin


class Recommendation(Base, TimestampMixin):
    __tablename__ = "recommendations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
    )
    recommendation_type: Mapped[str] = mapped_column(
        String(50), nullable=False
        # "document_gap" | "backup_expert" | "knowledge_transfer" | "risk_mitigation"
    )
    priority: Mapped[str] = mapped_column(
        String(20), nullable=False
        # "critical" | "high" | "medium" | "low"
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    target_entity_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    target_entity_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )
    risk_score_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("risk_scores.id", ondelete="SET NULL"),
        nullable=True,
    )
    evidence_ids: Mapped[list] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, default=list
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="open"
        # "open" | "in_progress" | "resolved" | "dismissed"
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    risk_score: Mapped["RiskScore | None"] = relationship("RiskScore")

    def __repr__(self) -> str:
        return (
            f"<Recommendation id={self.id} type={self.recommendation_type!r} "
            f"priority={self.priority!r} status={self.status!r}>"
        )
